### ISSUE TITLE
Prod error: 'bool' object has no attribute 'letter'

### ISSUE THREAD

**Issue by BryceStevenWilley** [SuffolkLITLab/docassemble-MAAffidavitDisclosingCareOrCustody#6]
Happened twice on Tuesday. Not familiar with the 209A structure, so I'm not exactly sure where it's coming from, just that [the `self.children` of some object](https://github.com/SuffolkLITLab/docassemble-MAVirtualCourt/blob/71df9db8f9e2518b65eef60a130285bd8494e654/docassemble/MAVirtualCourt/virtual_court_support.py#L134) is a list of bools, and not an object with the attribute letter.

```
AttributeError: 

    AttributeError: 'bool' object has no attribute 'letter'

Traceback (most recent call last):
  File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/docassemble/base/parse.py", line 8361, in assemble
    exec_with_trap(question, user_dict)
  File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/docassemble/base/parse.py", line 9754, in exec_with_trap
    exec(the_question.compute, the_dict)
  File "", line 9, in 
NameError: name 'A_affidavit_disclosing_care_or_custody_proceedings0009' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/docassemble/base/parse.py", line 9137, in askfor
    exec_with_trap(question, user_dict)
  File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/docassemble/base/parse.py", line 9754, in exec_with_trap
    exec(the_question.compute, the_dict)
  File "", line 42, in 
NameError: name 'removed_other_people_duplicates' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/docassemble/base/parse.py", line 9137, in askfor
    exec_with_trap(question, user_dict)
  File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/docassemble/base/parse.py", line 9754, in exec_with_trap
    exec(the_question.compute, the_dict)
  File "", line 4, in 
  File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/docassemble/base/util.py", line 2234, in __iter__
    self._trigger_gather()
  File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/docassemble/base/util.py", line 1690, in _trigger_gather
    self.gathered  # pylint: disable=pointless-statement
  File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/docassemble/base/util.py", line 937, in __getattr__
    raise docassemble.base.functions.this_thread.misc['pending_error']
docassemble.base.error.DAAttributeError: name 'others_in_proceedings.gathered' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/docassemble/webapp/server.py", line 8122, in index
    interview.assemble(user_dict, interview_status, old_user_dict, force_question=special_question)
  File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/docassemble/base/parse.py", line 8642, in assemble
    raise the_error
  File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/docassemble/base/parse.py", line 8429, in assemble
    question_result = self.askfor(missingVariable, user_dict, old_user_dict, interview_status, seeking=interview_status.seeking, follow_mc=follow_mc, seeking_question=seeking_question)
  File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/docassemble/base/parse.py", line 9252, in askfor
    question_result = self.askfor(newMissingVariable, user_dict, old_user_dict, interview_status, variable_stack=variable_stack, questions_tried=questions_tried, seeking=seeking, follow_mc=follow_mc, recursion_depth=recursion_depth, seeking_question=seeking_question)
  File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/docassemble/base/parse.py", line 9252, in askfor
    question_result = self.askfor(newMissingVariable, user_dict, old_user_dict, interview_status, variable_stack=variable_stack, questions_tried=questions_tried, seeking=seeking, follow_mc=follow_mc, recursion_depth=recursion_depth, seeking_question=seeking_question)
  File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/docassemble/base/parse.py", line 9137, in askfor
    exec_with_trap(question, user_dict)
  File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/docassemble/base/parse.py", line 9754, in exec_with_trap
    exec(the_question.compute, the_dict)
  File "", line 10, in 
  File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/docassemble/MAVirtualCourt/virtual_court_support.py", line 134, in child_letters
    return ''.join([child.letter for child in self.children if child.letter])
  File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/docassemble/MAVirtualCourt/virtual_court_support.py", line 134, in 
    return ''.join([child.letter for child in self.children if child.letter])
AttributeError: 'bool' object has no attribute 'letter'

The referer URL was https://apps.suffolklitlab.org/run/affofcare/

Traceback (most recent call last):
  File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/docassemble/base/parse.py", line 8361, in assemble
    exec_with_trap(question, user_dict)
  File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/docassemble/base/parse.py", line 9754, in exec_with_trap
    exec(the_question.compute, the_dict)
  File "", line 9, in 
NameError: name 'A_affidavit_disclosing_care_or_custody_proceedings0009' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/docassemble/base/parse.py", line 9137, in askfor
    exec_with_trap(question, user_dict)
  File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/docassemble/base/parse.py", line 9754, in exec_with_trap
    exec(the_question.compute, the_dict)
  File "", line 42, in 
NameError: name 'removed_other_people_duplicates' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/docassemble/base/parse.py", line 9137, in askfor
    exec_with_trap(question, user_dict)
  File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/docassemble/base/parse.py", line 9754, in exec_with_trap
    exec(the_question.compute, the_dict)
  File "", line 4, in 
  File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/docassemble/base/util.py", line 2234, in __iter__
    self._trigger_gather()
  File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/docassemble/base/util.py", line 1690, in _trigger_gather
    self.gathered  # pylint: disable=pointless-statement
  File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/docassemble/base/util.py", line 937, in __getattr__
    raise docassemble.base.functions.this_thread.misc['pending_error']
docassemble.base.error.DAAttributeError: name 'others_in_proceedings.gathered' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/docassemble/webapp/server.py", line 8122, in index
    interview.assemble(user_dict, interview_status, old_user_dict, force_question=special_question)
  File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/docassemble/base/parse.py", line 8642, in assemble
    raise the_error
  File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/docassemble/base/parse.py", line 8429, in assemble
    question_result = self.askfor(missingVariable, user_dict, old_user_dict, interview_status, seeking=interview_status.seeking, follow_mc=follow_mc, seeking_question=seeking_question)
  File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/docassemble/base/parse.py", line 9252, in askfor
    question_result = self.askfor(newMissingVariable, user_dict, old_user_dict, interview_status, variable_stack=variable_stack, questions_tried=questions_tried, seeking=seeking, follow_mc=follow_mc, recursion_depth=recursion_depth, seeking_question=seeking_question)
  File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/docassemble/base/parse.py", line 9252, in askfor
    question_result = self.askfor(newMissingVariable, user_dict, old_user_dict, interview_status, variable_stack=variable_stack, questions_tried=questions_tried, seeking=seeking, follow_mc=follow_mc, recursion_depth=recursion_depth, seeking_question=seeking_question)
  File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/docassemble/base/parse.py", line 9137, in askfor
    exec_with_trap(question, user_dict)
  File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/docassemble/base/parse.py", line 9754, in exec_with_trap
    exec(the_question.compute, the_dict)
  File "", line 10, in 
  File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/docassemble/MAVirtualCourt/virtual_court_support.py", line 134, in child_letters
    return ''.join([child.letter for child in self.children if child.letter])
  File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/docassemble/MAVirtualCourt/virtual_court_support.py", line 134, in 
    return ''.join([child.letter for child in self.children if child.letter])
AttributeError: 'bool' object has no attribute 'letter'

The external hostname was apps.suffolklitlab.org
```

**Comment by nonprofittechy** [comment]
More complete description in #7
