### ISSUE TITLE
 'bool' object has no attribute 'letter'

### ISSUE THREAD

**Issue by suffolklitlab-issues** [SuffolkLITLab/docassemble-MAAffidavitDisclosingCareOrCustody#7]
&nbsp; | &nbsp;
-------|------------------------------------
Question ID | `docket number`
Steps to reproduce | After docket number I keep getting an error page when I submit the info.
Expected behavior | The process to continue
What happened instead | An error page come up
Other information | 
Variable being sought | `docket_numbers[0]`
Package version | `0.0.9`

**Comment by nonprofittechy** [comment]
Found the relevant session and reproduced the issue:

```
    AttributeError: 'bool' object has no attribute 'letter'

Log

Traceback (most recent call last):
  File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/docassemble/base/parse.py", line 8361, in assemble
    exec_with_trap(question, user_dict)
  File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/docassemble/base/parse.py", line 9754, in exec_with_trap
    exec(the_question.compute, the_dict)
  File "<code block>", line 17, in <module>
NameError: name 'preview_screen' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/docassemble/base/parse.py", line 9172, in askfor
    return question.ask(user_dict, old_user_dict, the_x, iterators, missing_var, origMissingVariable)
  File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/docassemble/base/parse.py", line 5262, in ask
    eval(need_code, user_dict)
  File "<need expression>", line 1, in <module>
NameError: name 'form_to_sign' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/docassemble/base/parse.py", line 9137, in askfor
    exec_with_trap(question, user_dict)
  File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/docassemble/base/parse.py", line 9754, in exec_with_trap
    exec(the_question.compute, the_dict)
  File "<code block>", line 2, in <module>
NameError: name 'A_affidavit_disclosing_care_or_custody_proceedings0009_attachment_preview' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/docassemble/webapp/server.py", line 8122, in index
    interview.assemble(user_dict, interview_status, old_user_dict, force_question=special_question)
  File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/docassemble/base/parse.py", line 8642, in assemble
    raise the_error
  File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/docassemble/base/parse.py", line 8429, in assemble
    question_result = self.askfor(missingVariable, user_dict, old_user_dict, interview_status, seeking=interview_status.seeking, follow_mc=follow_mc, seeking_question=seeking_question)
  File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/docassemble/base/parse.py", line 9252, in askfor
    question_result = self.askfor(newMissingVariable, user_dict, old_user_dict, interview_status, variable_stack=variable_stack, questions_tried=questions_tried, seeking=seeking, follow_mc=follow_mc, recursion_depth=recursion_depth, seeking_question=seeking_question)
  File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/docassemble/base/parse.py", line 9252, in askfor
    question_result = self.askfor(newMissingVariable, user_dict, old_user_dict, interview_status, variable_stack=variable_stack, questions_tried=questions_tried, seeking=seeking, follow_mc=follow_mc, recursion_depth=recursion_depth, seeking_question=seeking_question)
  File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/docassemble/base/parse.py", line 9108, in askfor
    question.processed_attachments(user_dict, seeking_var=origMissingVariable, use_cache=False)
  File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/docassemble/base/parse.py", line 6482, in processed_attachments
    items.append([x, self.prepare_attachment(x, the_user_dict), None])
  File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/docassemble/base/parse.py", line 7136, in prepare_attachment
    answer = val.text(the_user_dict).rstrip()
  File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/docassemble/base/parse.py", line 1561, in text
    return self.template.render(**the_user_dict)
  File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/docassemble/base/mako/template.py", line 445, in render
    return runtime._render(self, self.callable_, args, data)
  File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/docassemble/base/mako/runtime.py", line 874, in _render
    _render_context(
  File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/docassemble/base/mako/runtime.py", line 916, in _render_context
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
  File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/docassemble/base/mako/runtime.py", line 943, in _exec_template
    callable_(context, *args, **kwargs)
  File "memory:0x7f959462d7b0", line 23, in render_body
  File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/docassemble/MAVirtualCourt/virtual_court_support.py", line 134, in child_letters
    return ''.join([child.letter for child in self.children if child.letter])
  File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/docassemble/MAVirtualCourt/virtual_court_support.py", line 134, in <listcomp>
    return ''.join([child.letter for child in self.children if child.letter])
AttributeError: 'bool' object has no attribute 'letter'
```

Specifically, it's tied to `other_care_custody_proceedings.children` being a list of True/False values.

![image](https://github.com/SuffolkLITLab/docassemble-MAAffidavitDisclosingCareOrCustody/assets/7645641/7c3442e2-277b-4174-b7b4-312e1ccbc44f)

**Comment by nonprofittechy** [comment]
Reproduced this on Prod, but not on the latest version of DA on apps-dev. Think it's worth upgrading production to see if that fixes this particular session.

This is the relevant question as far as I can tell:

```
id: about the other care or custody proceeding
need: DCF
question: |
  Tell us about the ${ordinal(i)} case involving ${comma_and_list(children_of_both, and_string=word("or"))}
subquestion: |
  Include the best information you know. If you’re not sure, it is okay to leave information blank or to write down what you remember.

  Only include information about cases that involve the children.

  You will have a chance to add more cases later.
fields:  
  - What is the best description of this case? You do not need the exact name.: other_care_custody_proceedings[i].case_status
    choices:
      - A different 209A restraining order: different 209A restraining order
      - Adoption: adoption
      - Annulment: annulment
      - Care and protection: care and protection
      - Child Requiring Assistance (CRA): CRA
      - Custody/Support/Parenting time: custody/support/parenting time
      - Custody/Support/Visitation: custody/support/visitation
      - Complaint to establish paternity: paternity
      - Divorce: divorce
      - Guardianship: guardianship
      - Separate support or other legal separation: separate support or legal separation
      - Other: other
  - This case happened outside of Massachusetts: other_care_custody_proceedings[i].non_ma_court
    datatype: yesno    
  - Name of court this case was filed in: other_care_custody_proceedings[i].court_name
    show if: other_care_custody_proceedings[i].non_ma_court
  - Name of court this case was filed in:  other_care_custody_proceedings[i].court_name
    hide if: other_care_custody_proceedings[i].non_ma_court
    datatype: combobox
    code: |
      sorted((set([str(y) for y in macourts.filter_courts(["District Court","Boston Municipal Court", "Probate and Family Court", "Superior Court", "Juvenile Court"])])))
  - Docket number or case number: other_care_custody_proceedings[i].docket_number
    required: False
  - Which children were involved in this case?: other_care_custody_proceedings[i].children
    datatype: object_checkboxes
    choices: |
      children_of_both
    none of the above: False
    minlength: 1
    show if:
      code: |
        len(children_of_both) > 1
  - What was your role in this case?: other_care_custody_proceedings[i].user_role
    datatype: radio
    choices:
      - Witness: W
      - Party: P
      - Other: O
      - I was not involved: N
    default: ${'N' if not has_participated_custody_case else ''}
    hide if: 
      variable: other_care_custody_proceedings[i].case_status
      is: adoption
  - Who else was part of this case?: other_care_custody_proceedings[i].other_party_types
    datatype: checkboxes
    choices:
      - ${other_parties.familiar()}: defendant
      - Department of Children and Families: dcf
      - Someone else (like a grandparent): other
  - Is this case still open?: other_care_custody_proceedings[i].is_open
    datatype: yesnoradio
    help: |
      Answer "yes" if the case is still ongoing. Choose no if a judge made a final decision,
      even if you or another person plans to appeal to it.
  - Was custody awarded?: other_care_custody_proceedings[i].custody_awarded
    js hide if: |
      val("other_care_custody_proceedings[i].case_status") == "adoption"
    datatype: yesnoradio      
  - Who was given custody?: other_care_custody_proceedings[i].person_given_custody
    js show if: |
      !(val("other_care_custody_proceedings[i].case_status") == "adoption") && val("other_care_custody_proceedings[i].custody_awarded")
  - Date custody was given: other_care_custody_proceedings[i].date_of_custody
    datatype: date
    js show if: |
      !(val("other_care_custody_proceedings[i].case_status") == "adoption")  && val("other_care_custody_proceedings[i].custody_awarded")
validation code: |
  # We don't ask the user to select which child is in the case if
  # there is only one child. Below code adds the child to the appropriate
  # list so we can write more general code.
  if len(children_of_both) == 1:
    other_care_custody_proceedings[i].children = children_of_both
```

Wondering if `object_checkboxes` briefly was returning a traditional checkbox and maybe it's fixed in latest?

**Comment by nonprofittechy** [comment]
Did confirm that `children_of_both` is a `PeopleList` as it should be
